services:
  sing-box:
    image: ghcr.io/cary17/sing-box:testing
    container_name: sing-box
    restart: unless-stopped
    network_mode: "host"
    cgroup: host
    environment:
      TZ: Asia/Shanghai
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON
    security_opt:
      - no-new-privileges:true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/sing-box/conf:/etc/sing-box/
      - /run/dbus:/run/dbus:ro
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
